Description: Budgets

Parameters:

  TotalCostLimit:
    Type: Number
    Description: Total organization cost limit in dollars

  NotificationEmail:
    Type: String
    Description: Email address where to send budget notifications

Resources:

  TotalCostBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: Total cost
        BudgetLimit:
          Amount: !Ref TotalCostLimit
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 50
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail